cassandra thrift_test.py true true
the_test is thrift_test.py
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.4.2, repeat-0.9.1, flaky-3.7.0
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 108 items

thrift_test.py::TestMutations::test_insert SKIPPED                       [  0%]
thrift_test.py::TestMutations::test_empty_slice SKIPPED                  [  1%]
thrift_test.py::TestMutations::test_cas SKIPPED                          [  2%]
thrift_test.py::TestMutations::test_missing_super SKIPPED                [  3%]
thrift_test.py::TestMutations::test_count SKIPPED                        [  4%]
thrift_test.py::TestMutations::test_count_paging SKIPPED                 [  5%]
thrift_test.py::TestMutations::test_count_around_page_size SKIPPED       [  6%]
thrift_test.py::TestMutations::test_super_insert SKIPPED                 [  7%]
thrift_test.py::TestMutations::test_super_get SKIPPED                    [  8%]
thrift_test.py::TestMutations::test_super_subcolumn_limit SKIPPED        [  9%]
thrift_test.py::TestMutations::test_long_order SKIPPED                   [ 10%]
thrift_test.py::TestMutations::test_integer_order SKIPPED                [ 11%]
thrift_test.py::TestMutations::test_time_uuid SKIPPED                    [ 12%]
thrift_test.py::TestMutations::test_long_remove SKIPPED                  [ 12%]
thrift_test.py::TestMutations::test_integer_remove SKIPPED               [ 13%]
thrift_test.py::TestMutations::test_batch_insert SKIPPED                 [ 14%]
thrift_test.py::TestMutations::test_batch_mutate_standard_columns SKIPPED [ 15%]
thrift_test.py::TestMutations::test_batch_mutate_remove_standard_columns SKIPPED [ 16%]
thrift_test.py::TestMutations::test_batch_mutate_remove_standard_row SKIPPED [ 17%]
thrift_test.py::TestMutations::test_batch_mutate_remove_super_columns_with_standard_under SKIPPED [ 18%]
thrift_test.py::TestMutations::test_batch_mutate_remove_super_columns_with_none_given_underneath SKIPPED [ 19%]
thrift_test.py::TestMutations::test_batch_mutate_remove_super_columns_entire_row SKIPPED [ 20%]
thrift_test.py::TestMutations::test_batch_mutate_remove_slice_standard SKIPPED [ 21%]
thrift_test.py::TestMutations::test_batch_mutate_remove_slice_of_entire_supercolumns SKIPPED [ 22%]
thrift_test.py::TestMutations::test_batch_mutate_remove_slice_part_of_supercolumns SKIPPED [ 23%]
thrift_test.py::TestMutations::test_batch_mutate_insertions_and_deletions SKIPPED [ 24%]
thrift_test.py::TestMutations::test_bad_system_calls SKIPPED             [ 25%]
thrift_test.py::TestMutations::test_bad_batch_calls SKIPPED              [ 25%]
thrift_test.py::TestMutations::test_column_name_lengths SKIPPED          [ 26%]
thrift_test.py::TestMutations::test_bad_calls SKIPPED                    [ 27%]
thrift_test.py::TestMutations::test_batch_insert_super SKIPPED           [ 28%]
thrift_test.py::TestMutations::test_cf_remove_column SKIPPED             [ 29%]
thrift_test.py::TestMutations::test_cf_remove SKIPPED                    [ 30%]
thrift_test.py::TestMutations::test_super_cf_remove_and_range_slice SKIPPED [ 31%]
thrift_test.py::TestMutations::test_super_cf_remove_column SKIPPED       [ 32%]
thrift_test.py::TestMutations::test_super_cf_remove_supercolumn SKIPPED  [ 33%]
thrift_test.py::TestMutations::test_super_cf_resurrect_subcolumn SKIPPED [ 34%]
thrift_test.py::TestMutations::test_empty_range SKIPPED                  [ 35%]
thrift_test.py::TestMutations::test_super_cql_read_compatibility SKIPPED [ 36%]
thrift_test.py::TestMutations::test_super_cql_write_compatibility SKIPPED [ 37%]
thrift_test.py::TestMutations::test_range_with_remove SKIPPED            [ 37%]
thrift_test.py::TestMutations::test_range_with_remove_cf SKIPPED         [ 38%]
thrift_test.py::TestMutations::test_range_collation SKIPPED              [ 39%]
thrift_test.py::TestMutations::test_range_partial SKIPPED                [ 40%]
thrift_test.py::TestMutations::test_get_slice_range SKIPPED              [ 41%]
thrift_test.py::TestMutations::test_get_slice_super_range SKIPPED        [ 42%]
thrift_test.py::TestMutations::test_get_range_slices_tokens SKIPPED      [ 43%]
thrift_test.py::TestMutations::test_get_range_slice_super SKIPPED        [ 44%]
thrift_test.py::TestMutations::test_get_range_slice SKIPPED              [ 45%]
thrift_test.py::TestMutations::test_wrapped_range_slices SKIPPED         [ 46%]
thrift_test.py::TestMutations::test_get_slice_by_names SKIPPED           [ 47%]
thrift_test.py::TestMutations::test_multiget_slice_with_compact_table SKIPPED [ 48%]
thrift_test.py::TestMutations::test_multiget_slice SKIPPED               [ 49%]
thrift_test.py::TestMutations::test_multi_count SKIPPED                  [ 50%]
thrift_test.py::TestMutations::test_batch_mutate_super_deletion SKIPPED  [ 50%]
thrift_test.py::TestMutations::test_super_reinsert SKIPPED               [ 51%]
thrift_test.py::TestMutations::test_describe_keyspace SKIPPED            [ 52%]
thrift_test.py::TestMutations::test_describe SKIPPED                     [ 53%]
thrift_test.py::TestMutations::test_describe_ring SKIPPED                [ 54%]
thrift_test.py::TestMutations::test_describe_token_map SKIPPED           [ 55%]
thrift_test.py::TestMutations::test_describe_partitioner SKIPPED         [ 56%]
thrift_test.py::TestMutations::test_describe_snitch SKIPPED              [ 57%]
thrift_test.py::TestMutations::test_invalid_ks_names SKIPPED             [ 58%]
thrift_test.py::TestMutations::test_invalid_strategy_class SKIPPED       [ 59%]
thrift_test.py::TestMutations::test_invalid_cf_names SKIPPED             [ 60%]
thrift_test.py::TestMutations::test_system_cf_recreate SKIPPED           [ 61%]
thrift_test.py::TestMutations::test_system_keyspace_operations SKIPPED   [ 62%]
thrift_test.py::TestMutations::test_create_then_drop_ks SKIPPED          [ 62%]
thrift_test.py::TestMutations::test_column_validators SKIPPED            [ 63%]
thrift_test.py::TestMutations::test_system_column_family_operations SKIPPED [ 64%]
thrift_test.py::TestMutations::test_dynamic_indexes_creation_deletion SKIPPED [ 65%]
thrift_test.py::TestMutations::test_dynamic_indexes_with_system_update_cf SKIPPED [ 66%]
thrift_test.py::TestMutations::test_system_super_column_family_operations SKIPPED [ 67%]
thrift_test.py::TestMutations::test_insert_ttl SKIPPED                   [ 68%]
thrift_test.py::TestMutations::test_insert_max_ttl SKIPPED               [ 69%]
thrift_test.py::TestMutations::test_insert_max_default_ttl SKIPPED       [ 70%]
thrift_test.py::TestMutations::test_simple_expiration SKIPPED            [ 71%]
thrift_test.py::TestMutations::test_expiration_with_default_ttl SKIPPED  [ 72%]
thrift_test.py::TestMutations::test_expiration_with_default_ttl_and_zero_ttl SKIPPED [ 73%]
thrift_test.py::TestMutations::test_simple_expiration_batch_mutate SKIPPED [ 74%]
thrift_test.py::TestMutations::test_update_expiring SKIPPED              [ 75%]
thrift_test.py::TestMutations::test_remove_expiring SKIPPED              [ 75%]
thrift_test.py::TestMutations::test_describe_ring_on_invalid_keyspace SKIPPED [ 76%]
thrift_test.py::TestMutations::test_incr_decr_standard_add SKIPPED       [ 77%]
thrift_test.py::TestMutations::test_incr_decr_super_add SKIPPED          [ 78%]
thrift_test.py::TestMutations::test_incr_standard_remove SKIPPED         [ 79%]
thrift_test.py::TestMutations::test_incr_super_remove SKIPPED            [ 80%]
thrift_test.py::TestMutations::test_incr_decr_standard_remove SKIPPED    [ 81%]
thrift_test.py::TestMutations::test_incr_decr_super_remove SKIPPED       [ 82%]
thrift_test.py::TestMutations::test_incr_decr_standard_batch_add SKIPPED [ 83%]
thrift_test.py::TestMutations::test_incr_decr_standard_batch_remove SKIPPED [ 84%]
thrift_test.py::TestMutations::test_range_deletion SKIPPED               [ 85%]
thrift_test.py::TestMutations::test_range_deletion_eoc_0 SKIPPED         [ 86%]
thrift_test.py::TestMutations::test_incr_decr_standard_slice SKIPPED     [ 87%]
thrift_test.py::TestMutations::test_incr_decr_standard_multiget_slice SKIPPED [ 87%]
thrift_test.py::TestMutations::test_counter_get_slice_range SKIPPED      [ 88%]
thrift_test.py::TestMutations::test_counter_get_slice_super_range SKIPPED [ 89%]
thrift_test.py::TestMutations::test_index_scan SKIPPED                   [ 90%]
thrift_test.py::TestMutations::test_index_scan_uuid_names SKIPPED        [ 91%]
thrift_test.py::TestMutations::test_index_scan_expiring SKIPPED          [ 92%]
thrift_test.py::TestMutations::test_index_scan_indexed_column_outside_slice_predicate SKIPPED [ 93%]
thrift_test.py::TestMutations::test_column_not_found_quorum SKIPPED      [ 94%]
thrift_test.py::TestMutations::test_get_range_slice_after_deletion SKIPPED [ 95%]
thrift_test.py::TestMutations::test_multi_slice SKIPPED                  [ 96%]
thrift_test.py::TestMutations::test_truncate SKIPPED                     [ 97%]
thrift_test.py::TestMutations::test_cql_range_tombstone_and_static SKIPPED [ 98%]
thrift_test.py::TestMutations::test_compact_storage_get SKIPPED          [ 99%]
thrift_test.py::TestMutations::test_range_tombstone_eoc_0 SKIPPED        [100%]

========================= 108 skipped in 25.83 seconds =========================
[msx] rc = 0
